# Generated by Django 4.0.5 on 2022-11-16 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tutorial_request', '0001_initial'),
        ('tutorial_calification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=10)),
                ('start_time', models.TimeField()),
                ('topics_covered', models.TextField(max_length=150)),
                ('state', models.IntegerField(choices=[(0, 'Sin calificar'), (1, 'Calificada')], default=0)),
                ('student_calification', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial_calification.studentcalification')),
                ('tutor_calification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tutorial_calification.tutorcalification')),
                ('tutorial_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tutorial_request.tutorial_request')),
            ],
            options={
                'verbose_name': 'Tutoría',
                'verbose_name_plural': 'Tutorías',
            },
        ),
    ]
