# Generated by Django 4.0.5 on 2022-11-16 02:35

from django.db import migrations, models
import request_tutor.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request_to_tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=50)),
                ('time', models.CharField(default='', max_length=20)),
                ('SEA', models.BooleanField(default=False)),
                ('need_hours', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('response_date', models.DateField(auto_now_add=True)),
                ('certificate', models.FileField(default='', upload_to='certifications/', validators=[request_tutor.validators.validate_file_extension])),
                ('request_state', models.CharField(choices=[(0, 'Espera'), (1, 'Aprobado'), (2, 'Rechazado')], default=0, max_length=15)),
            ],
            options={
                'verbose_name': 'Solicitud para ser tutor',
                'verbose_name_plural': 'Solicitudes para ser tutor',
            },
        ),
    ]
