# Generated by Django 4.0.5 on 2022-11-16 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCalification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(choices=[(None, 'Califica del 1 al 5'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('feedback', models.TextField(blank=True, max_length=200, null=True)),
                ('tutor_behavior', models.IntegerField(choices=[(None, 'Califica del 1 al 5'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1)),
                ('how_know', models.TextField(blank=True, choices=[('SOCIAL_MEDIA', 'Redes sociales'), ('OFFICE', 'Oficina de bienestar 18-119a'), ('EMAIL', 'Correo electrónico'), ('WEB', 'Portal universitario'), ('OTHER', 'Otro')], default='SOCIAL_MEDIA', max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Calificación dada por el estudiante',
                'verbose_name_plural': 'Calificación dada por el estudiante',
            },
        ),
        migrations.CreateModel(
            name='TutorCalification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(choices=[(None, 'Califica del 1 al 5'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('feedback', models.TextField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Calificación de tutoría',
                'verbose_name_plural': 'Calificaciones de las tutorías',
            },
        ),
    ]
