# Generated by Django 4.0.5 on 2022-11-16 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signup', '0001_initial'),
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='tutors',
            field=models.ManyToManyField(to='signup.tutor'),
        ),
    ]
