# Generated by Django 4.0.5 on 2022-11-16 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academic_Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modality', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('program_code', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Programa académico',
                'verbose_name_plural': 'Programas académicos',
            },
        ),
    ]
